update

diff --git a/test/runtest b/test/runtest
--- a/test/runtest
+++ b/test/runtest
@@ -15,32 +15,38 @@ do
     rm -f temp/test_build.jar
 
     # compiling
-    cp $test_dir/output temp/current/test.ideal
     javac -d temp/test_build $test_dir/source/*.java 
-    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;32mFailed: JCE\e[0m"; exit $rc; fi
+    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;31mFailed: JCE\e[0m"; exit $rc; fi
     jar cvfe temp/test_build.jar Test -C temp/test_build/ .
-    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;32mFailed: JE\e[0m"; exit $rc; fi
+    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;31mFailed: JE\e[0m"; exit $rc; fi
 
     # making test
     java -jar native-obfuscator.jar temp/test_build.jar temp/current
-    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;32mFailed: NOE\e[0m"; exit $rc; fi
+    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;31mFailed: NOE\e[0m"; exit $rc; fi
     cd temp/current/cpp
     cmake .
-    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;32mFailed: PCE\e[0m"; exit $rc; fi
+    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;31mFailed: PCE\e[0m"; exit $rc; fi
     cmake --build . --config Release
-    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;32mFailed: CE\e[0m"; exit $rc; fi
+    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;31mFailed: CE\e[0m"; exit $rc; fi
     cd ../../..
     cp temp/current/cpp/build/lib/* temp/current/
+
+    # ideal output
+    cd temp
+    java -jar test_build.jar > test.ideal
+    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;31mFailed: IRE\e[0m"; exit $rc; fi
+    cd ..
+    cp temp/test.ideal temp/current/test.ideal
 
     # testing
     cd temp/current
     java -Djava.library.path=. -jar test_build.jar > test.no
-    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;32mFailed: RE\e[0m"; exit $rc; fi
+    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;31mFailed: NRE\e[0m"; exit $rc; fi
     cd ../..
 
     # checking
     cmp -s temp/current/test.no temp/current/test.ideal
-    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;32mFailed: WA\e[0m"; exit $rc; fi
+    rc=$?; if [[ $rc != 0 ]]; then echo -e "\e[1;31mFailed: WA\e[0m"; exit $rc; fi
 
     echo -e "\e[1;32mOK\e[0m"
 done
